# Explicit Netlify build command that installs with legacy-peer-deps then builds.
[build]
  # Use npm ci for reproducible installs and force legacy peer deps; fallback to npm install if no package-lock
  command = "npm run build"
  # plugin will set the correct publish dir (.netlify/next) so you can leave this blank or set to ".netlify/next"
  publish = "out"

# If you later need App Router / SSR support, revert to using the Netlify Next.js plugin:
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
# and change the build command back to "npm run build" (plugin will produce .netlify/next).
# [build]
#   command = "npm run build:export"
#   publish = "out"
# and remove the [[plugins]] section.
# (Then comment out or remove the [[plugins]] section above.)
