# Explicit Netlify build command that installs with legacy-peer-deps then builds.
[build]
  # Use npm ci for reproducible installs and force legacy peer deps; fallback to npm install if no package-lock
  command = "npm run build"
  # plugin will set the correct publish dir (.netlify/next) so you can leave this blank or set to ".netlify/next"
  publish = ".netlify/next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# --- If you prefer a static export workflow instead of the plugin, use:
# [build]
#   command = "npm run build:export"
#   publish = "out"
#
# (Then comment out or remove the [[plugins]] section above.)
